### ISSUE TITLE
为什么番名是日文的

### ISSUE THREAD

**Issue by HuangGuoY** [deepred5/daily-anime#4]
截图不是中文的吗- -

**Comment by deepred5** [comment]
@GuoMiaoMiao 要设置vscode的[语言环境](https://code.visualstudio.com/docs/getstarted/locales)，`locale`是`zh-CN`或者`zh-TW`时，才展示中文，否则是日文。

**Comment by HuangGuoY** [comment]
@deepred5 哦，原来如此 3q
